### ISSUE TITLE
What's the difference between the models in the "pretrained model" link?

### ISSUE THREAD

**Issue by Charlottecuc** [SungFeng-Huang/Meta-TTS#1]
Hi. The work is amazing. If I want to test the model, which pretrained model should I use? (Because I notice that the filenames in the pretrained model link are quite similar)
I also notice that in the demo page (Section 4.3), you only did parallel voice cloning with unseen speakers, have you tried testing with different text with these speakers? 
Thank you very much.

**Comment by SungFeng-Huang** [comment]
Hi, may I ask where did you see my paper? There are several versions, but none of them are publicly released... so I want to make sure that this is the correct repository you're finding.
Also, some versions do not mention the difference between those pretrained models, so I need to check whether I need to further explain.

To compare the pretrained models, you can check out the ``README.md`` of [an earlier commit](https://github.com/SungFeng-Huang/Meta-TTS/tree/d13df31e211c142c0cf48d7199bdee60b921ed1e), which is the last commit (no bug but dirty code) that we can directly use the checkpoints.
For the newer commits, we refactored the codes and some modules are renamed, so we need to fix those module names of the checkpoints before using them.

At last, I'm not sure "have you tried testing with different text with these speakers?" refers to seen or unseen speakers? For unseen speakers, we test our models by fine-tuning on 5 utterances then generate a new utterance from the 6th utterance's text, so the testing text is never used during training/fine-tuning.

Hope I answered your question!

**Comment by Charlottecuc** [comment]
Hi. Thank you for your reply. 
Yes, you are right. I mistook this repo for Meta-Style Speech...
