### ISSUE TITLE
incompatible package versions

### ISSUE THREAD

**Issue by 1417889711** [SungFeng-Huang/Meta-TTS#6]
感谢您的贡献。我是一名学生，想以您的Meta-TTS模型作为基线模型或者对照组来完成我的毕业论文，因此需要复现您的代码。但在复现过程中出现了一些预料之外的bug比如安装包不兼容情况等，如果可能的话，希望您提供requiremengts.txt中包的版本，或者我应该复现之前版本的代码（可以使用您的预训练模型）。我想在您的预训练模型上进行推理，如果您能给到我一些宝贵的建议我将感激不尽。

**Comment by SungFeng-Huang** [comment]
能請您提供安裝時的error message嗎？我最近更新套件版本時並沒有明確出現問題，過去經驗中較容易出現的安裝問題主要是pytorch/torchaudio/torchtext彼此版本的不匹配，這部分可以參考[我在另一個repo的回覆](https://github.com/SungFeng-Huang/SSL-pretraining-separation/issues/1#issuecomment-762970476)。若要直接使用pretrained checkpoint，目前確認可直接執行的程式版本是[這個commit](https://github.com/SungFeng-Huang/Meta-TTS/tree/d13df31e211c142c0cf48d7199bdee60b921ed1e)。
Hope these helps，也祝我們彼此都畢業順利！

**Comment by 1417889711** [comment]
非常感谢您的及时解答。在您的建议下我更换了commit，但在执行到Processing中的python3 preprocess.py config/LibriTTS/preprocess.yaml时依然出现了包不兼容的错误：
File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
这个错误看起来是numpy与puyworld不兼容导致的，在我将numpy=1.19.2升级到1.20时依然存在这个问题，于是我将pyworld=0.3.2改到0.3.0时解决了这个问题。但是与此同时又产生了新的问题：
OSError: /home/yuexin/anaconda3/envs/metatts-1/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
这个错误看起来是torch版本跟cublas不兼容导致的，于是我将torch=1.13.1改到1.9.1版本，从而解决了上述问题。
但在更改完torch版本后出现了新的红色警告：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1 requires torch==1.13.1, but you have torch 1.9.1 which is incompatible.
torchaudio 0.13.1 requires torch==1.13.1, but you have torch 1.9.1 which is incompatible.
pytorch-lightning 1.9.3 requires torch>=1.10.0, but you have torch 1.9.1 which is incompatible.
我不确定这是否会导致新的问题，所以可能的话希望您能提供成功运行时的各种安装包的版本。
再次感谢！

**Comment by 1417889711** [comment]
我觉得问题可能出在这个地方：在运行pip install -r requirement.txt 时，系统给我安装的各个包版本跟您执行时的版本并不相同，所以会导致接下来的错误

**Comment by SungFeng-Huang** [comment]
> 但在更改完torch版本后出现了新的红色警告：
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> torchvision 0.14.1 requires torch==1.13.1, but you have torch 1.9.1 which is incompatible.
> torchaudio 0.13.1 requires torch==1.13.1, but you have torch 1.9.1 which is incompatible.
> pytorch-lightning 1.9.3 requires torch>=1.10.0, but you have torch 1.9.1 which is incompatible.

這個就是我說的pytorch/torchaudio/torchtext彼此版本的不匹配問題，可以參考[我在另一個repo的回覆](https://github.com/SungFeng-Huang/SSL-pretraining-separation/issues/1#issuecomment-762970476)

至於我自己的package版本，因為我是偶爾想到才升級，基本上也沒有出錯，所以就沒有特別限定。以下是我目前環境的版本：
learn2learn                   0.1.7
comet-ml                      3.22.0
g2p-en                        2.1.0
inflect                       5.3.0
librosa                       0.9.2
matplotlib                    3.6.3
matplotlib-inline             0.1.3
numba                         0.56.4
numpy                         1.23.5
pypinyin                      0.44.0
pyworld                       0.3.0
PyYAML                        6.0
scikit-learn                  1.2.1
scipy                         1.9.3
soundfile                     0.11.0
tensorboard                   2.11.2
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.0
tgt                           1.4.4
hypergrad                     0.1         /home/r06942045/myProjects/Meta-TTS/hypertorch
pytorch-lightning             1.6.4
torch                         1.13.1
torchaudio                    0.9.1
torchmeta                     1.8.0
torchmetrics                  0.9.0
torchvision                   0.14.1
tqdm                          4.64.1
torchaudio                    0.9.1
seaborn                       0.11.2

**Comment by 1417889711** [comment]
感谢您的回复。但我发现您的包也有冲突的地方，比如torch 1.13.1与torchaudio 0.9.1是冲突的，请问是之前用的torch1.9.1然后再升级到1.13.1的吗，现在您是不是只是test而没有再train模型了

**Comment by 1417889711** [comment]
Using cache found in /home/yuexin/.cache/torch/hub/descriptinc_melgan-neurips_master
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    main(args, configs)
  File "main.py", line 105, in main
    model = system(
  File "/home/yuexin/Downloads/Meta-TTS-main/lightning/systems/baseline.py", line 20, in __init__
    super().__init__(*args, **kwargs)
  File "/home/yuexin/Downloads/Meta-TTS-main/lightning/systems/base_adaptor.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/home/yuexin/Downloads/Meta-TTS-main/lightning/systems/system.py", line 47, in __init__
    self.vocoder = LightningMelGAN()
  File "/home/yuexin/Downloads/Meta-TTS-main/lightning/utils.py", line 11, in __init__
    vocoder = torch.hub.load(
  File "/home/yuexin/anaconda3/envs/metatts/lib/python3.8/site-packages/torch/hub.py", line 382, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/yuexin/anaconda3/envs/metatts/lib/python3.8/site-packages/torch/hub.py", line 411, in _load_local
    model = entry(*args, **kwargs)
  File "/home/yuexin/.cache/torch/hub/descriptinc_melgan-neurips_master/hubconf.py", line 16, in load_melgan
    return MelVocoder(path=None, github=True, model_name=model_name)
  File "/home/yuexin/.cache/torch/hub/descriptinc_melgan-neurips_master/mel2wav/interface.py", line 38, in __init__
    self.fft = Audio2Mel().to(device)
  File "/home/yuexin/.cache/torch/hub/descriptinc_melgan-neurips_master/mel2wav/modules.py", line 42, in __init__
    mel_basis = librosa_mel_fn(
TypeError: mel() takes 0 positional arguments but 5 were given

此外在运行Meta-TTS-main分支的main来train时候报了这个错误，看起来是MelVocoder构造函数中使用了librosa_mel_fn，该函数传入5个位置参数，但是没有被接收， 有没有可能是因为库的版本问题导致函数的参数发生了变化

**Comment by SungFeng-Huang** [comment]
> 感谢您的回复。但我发现您的包也有冲突的地方，比如torch 1.13.1与torchaudio 0.9.1是冲突的，请问是之前用的torch1.9.1然后再升级到1.13.1的吗，现在您是不是只是test而没有再train模型了

我還是有在train誒，雖然不是meta的部分，但像是baseline還是train的起來啊？不過我確實是從1.9.1升上去的，您可以再試試

**Comment by SungFeng-Huang** [comment]
> "/home/yuexin/.cache/torch/hub/descriptinc_melgan-neurips_master/mel2wav/modules.py", line 42, in **init** mel_basis = librosa_mel_fn( TypeError: mel() takes 0 positional arguments but 5 were given
> 
> 此外在运行Meta-TTS-main分支的main来train时候报了这个错误，看起来是MelVocoder构造函数中使用了librosa_mel_fn，该函数传入5个位置参数，但是没有被接收， 有没有可能是因为库的版本问题导致函数的参数发生了变化

這感覺是您的librosa有問題誒？就算是最新的[librosa.filters.mel](https://librosa.org/doc/main/generated/librosa.filters.mel.html)也是有用兩個positional arguments的（sr, n_fft），而且後面的keywork arguments理論上也要可以照順序assign，您的error message比較像是您的系統以為mel()完全沒有argument，這反倒很奇怪？

**Comment by 1417889711** [comment]
感谢您的及时回复。如您所言，确实是librosa版本有问题，在将版本改为 0.9.2后解决了这个问题。
