### ISSUE TITLE
update evaluation/README

### ISSUE THREAD

**Issue by 1417889711** [SungFeng-Huang/Meta-TTS#7]
您好，冒昧打扰，望海涵。
看到您的evaluation/README中有提到Utilizing Self-supervised Representations for MOS Prediction这篇论文，不确定是不是这篇已发布的代码：[https://github.com/s3prl/s3prl/tree/master/s3prl/upstream/mos_prediction](url)
如果是的话不知道您是否方便更新一下evaluation/README。
感激不尽。
敬颂春祺

**Comment by SungFeng-Huang** [comment]
確實是那份代碼沒錯，我當初發表論文時代碼還沒公開，所以才沒註明在readme。
我的最新更新都在refactor branch，因為目前還沒完成一份完整的版本所以才都沒有更新到master branch。
等我持續更新完所有功能並refactor完之後就會merge回master了。
