### ISSUE TITLE
Is 4 positive samples and 4 negative samples enough for computing the threshold for asv acceptant rate?

### ISSUE THREAD

**Issue by predawnang** [SungFeng-Huang/Meta-TTS#8]
Hi,

I noticed that in the evaluation/json/VCTK/pair.json you provide 4 positive samples and 4 negative samples per speaker in vctk dataset. I wonder that is it enough for computing a good threshold value for asv acceptant rate?

Thanks

**Comment by SungFeng-Huang** [comment]
Hi,

We are following the settings of [VoxCeleb](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1.html), a commonly used corpus for automatic speaker verification (ASV) tasks. As VoxCeleb is widely accepted among ASV researchers, we believe that the number of positive and negative samples provided is sufficient for ASV purposes.

**Comment by predawnang** [comment]
thank you so much
